# espanso 测试配置文件
matches:
  - trigger: ":hello"
    replace: "你好，世界！"
  - trigger: ":test"
    replace: "这是一个测试"
  - trigger: ":date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d" 