name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # 当一个 v 开头的 tag 被推送时触发，例如 v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }} # 根据 matrix 中的 os 运行在不同的操作系统上

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest] # 定义要打包的平台
        node-version: [18.x] # 定义 Node.js 版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # 如果你使用 pnpm，可以缓存依赖

      - name: Install dependencies
        run: pnpm install # 或者 npm install / yarn install

      - name: Build application
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            pnpm run electron:build:mac
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            pnpm run electron:build:win
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pnpm run electron:build:linux
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # electron-builder 可能需要这个来发布

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} # 获取 Release 的上传 URL
          asset_path: | # 这里需要根据 electron-builder 的输出路径和文件名来调整
            dist_electron/**/*.dmg
            dist_electron/**/*.exe
            dist_electron/**/*.AppImage
            dist_electron/**/*.deb
            dist_electron/**/*.rpm
            dist_electron/**/*.snap
          asset_content_type: application/octet-stream
